# Tomcat
server:
  port: 7887

config:
  server:
    zk: 127.0.0.1:2181
    project: /drinks/milk
    version: 1.0
    group: develop
rocketmq:
  accessKey: LTAI4G9Rgd5be4uZy13yACHB
  secretKey: oSMigromzWPm42GoFpuTaJHvgGfWuj
  #  nameSrvAddr: http://MQ_INST_1856830781567171_BXbvuwWU.cn-beijing.mq-internal.aliyuncs.com:8080
  nameSrvAddr: http://MQ_INST_1856830781567171_BXeFT1Ya.mq-internet-access.mq-internet.aliyuncs.com:80
  topic: NOTICE_MSG
  groupId: GID_NOTICE_MSG
  #定时/延时消息
  timeTopic: TRAIN_MSG
  timeGroupId: GID_TRAIN_MSG